### ISSUE TITLE
spawn issue in tauri

### ISSUE THREAD

**Issue by bburdette** [j-tai/girlboss#2]
Hi j-tai!

_girlboss_ is working well for me in my web server.  But, I also use that web server as a library for a tauri app.  

The issue I'm experiencing there is that the task never starts.  I checked out girlboss and put in a [bunch of printlns](https://github.com/j-tai/girlboss/compare/main...bburdette:girlboss:spawn-debug).  

It gets to the point where it [calls tokio::spawn](https://github.com/bburdette/girlboss/blob/97c4664e2e29302706bbad0565a409f25686585d/src/job.rs#L77), but the task itself never printlns.  

I tried a plain tauri::spawn and it was able to kick off a task - "I'm in the spawn" below.  

```
      info!("PrivateRequests::SyncRemote");
      let dbpath: PathBuf = state.config.orgauth_config.db.to_path_buf();
      let file_path: PathBuf = state.config.file_path.to_path_buf();
      let uid: i64 = uid;

      let jid = new_jobid(state, uid);
      info!("SyncRemote jobid: {:?}", jid);

      println!("right here");

      let jh = tokio::spawn(async {
        println!("I'm in the spawn");
      });

      println!("await: {:?} ", jh.await);

      let job = state
        .girlboss
        .start(jid, move |mon| async move {
          println!("gb thread");
          let gbm = GirlbossMonitor { monitor: mon };
          // spawn thread, local runtime.  success.
          std::thread::spawn(move || {
            println!("sync thread");
            let rt = Runtime::new().unwrap();
            let local = LocalSet::new();
            let mut callbacks = &mut zknotes_callbacks();
            write!(gbm, "starting sync");
            let r = local.block_on(
              &rt,
              sync::sync(&dbpath, &file_path, uid, &mut callbacks, &gbm),
            );
            match r {
              Ok(_) => write!(gbm, "sync completed"),
              Err(e) => write!(gbm, "sync err: {:?}", e),
            }
          });
        })
        .await?;

      info!("job: {:?}", job);
```

the sequence of printlns below.  (info! goes to a separate file right now)

```
right here
I'm in the spawn
await: Ok(())
girlboss-manager::start
girlboss-manager::start2
girlboss-manager::start3
girlboss-job::start1
girlboss-job::start2
girlboss-job::start3
girlboss-job::start7
girlboss-manager::start4
sr: JobStatus
zimsg
```

So, there's some unwanted interaction between girlboss and tauri, it seems.  Got any ideas what might be going on?  TY!

**Comment by j-tai** [comment]
Huh, that's strange. I wonder if you're somehow blocking tokio's threads...?

What happens if you put a sleep right after creating the job?
```rust
tokio::time::sleep(Duration::from_millis(100)).await;
```

**Comment by bburdette** [comment]
Whoa, that worked!  The whole process completes normally now.  What does it mean?

```
right here
I'm in the spawn
await: Ok(())
girlboss-manager::start
girlboss-manager::start2
girlboss-manager::start3
girlboss-job::start1
girlboss-job::start2
girlboss-job::start3
girlboss-job::start7
girlboss-manager::start4
girlboss-job::start4
gb thread
girlboss-job::start5
girlboss-job::start6
sync thread
sr: JobStatus
zimsg
sr: JobStatus
```

**Comment by j-tai** [comment]
How interesting. I suspect that the Tokio runtime is, for some reason, not getting a chance to run the spawned task. Here are some possible causes that I can think of:

* Your Tokio runtime might be initialized as single-threaded. If you're initializing the runtime yourself (e.g. with `#[tokio::main]` or `tokio::runtime::Builder` or something), perhaps you set it to single-threaded by mistake. If Tauri is initializing it, perhaps they set up tokio to be single-threaded by default (I'm not familiar with Tauri). Or maybe you set the `TOKIO_WORKER_THREADS` environment variable...
* You might be blocking Tokio's thread -- not necessarily here, but anywhere in your program. This can happen if you mistakenly use a blocking function inside async code, or if you're running CPU-intensive code on a Tokio thread. More info: https://docs.rs/tokio/1.41.1/tokio/#cpu-bound-tasks-and-blocking-code
* Some combination of the two.

**Comment by bburdette** [comment]
I'm pretty sure I found the problem - going back up the call chain it turns out I had created an actix_rt in which to run my web handler in tauri, since it's !Send and actix_rt is ok with that.  Its been long enough that I forgot all about it!  So yeah, single threaded runtime.  

I probably won't have time to work on it the next few days, but seems solvable now, will post back when its working.

**Comment by bburdette** [comment]
Both the trouble runtime, and the one where it was working (actix_web handler) report num_workers of 1.  But in one case it works and the other not so much.  

tokio metrics in both:
```
num_workers 1
num_alive_tasks 0
global_queue_depth 0
```

Sort-of solved the problem by using a non-async handler in tauri.  GB can start a job in that and it works without needing the `sleep`.  Don't really get it, but I think I'm going to leave it there for now, so I'm closing this issue.

**Comment by j-tai** [comment]
Hi @bburdette, I've published a new version (`1.0.0-alpha.1`) which supports both tokio and actix-rt. If you have time, would you be able to check it out & provide feedback? :)

Hopefully, since girlboss now supports actix-rt directly, you won't need the `std::thread::spawn` workaround anymore.

**Update**: I released `1.0.0-alpha.3` which fixes the [documentation on docs.rs](https://docs.rs/girlboss/1.0.0-alpha.3/girlboss/index.html).

**Comment by bburdette** [comment]
cool!  I'll give it a try when I get a chance!

**Comment by bburdette** [comment]
Finally circling back to this.  I'm having trouble using the new girlboss in my actix_web state:

https://github.com/bburdette/zknotes/blob/1dbfec7dd30844ad870902a4562cbecfffdd5bde/server-lib/src/state.rs#L6

The compile error is:

```
error[E0277]: `RefCell<std::option::Option<tokio::task::JoinHandle<()>>>` cannot be shared between threads safely
   --> server-lib/src/lib.rs:864:32
    |
864 |     let server = HttpServer::new(move || {
    |  ________________---------------_^
    | |                |
    | |                required by a bound introduced by this call
865 | |     let staticpath = c.static_path.clone().unwrap_or(PathBuf::from("static/"));
866 | |     let d = c.clone();
867 | |     let cors = Cors::default()
...   |
913 | |       .service(web::resource("/{tail:.*}").route(web::get().to(mainpage)))
914 | |   })
    | |___^ `RefCell<std::option::Option<tokio::task::JoinHandle<()>>>` cannot be shared between threads safely
 ```

**Comment by j-tai** [comment]
For actix-rt, you need to create a separate `Girlboss` instance per thread. That's because each actix-rt task (and hence, each girlboss `Job`) is confined to its own runtime.

**Comment by bburdette** [comment]
Ok done!  That works, I can kick off the sync task that way in my actix_web server.   

But I'm hazy on how to do job tracking under this regime.  When a request comes in to the web server to inquire about a job, I can't return any information since the gb manager cannot be stored in the web server state.  Plus each thread requires its own Girlboss manager, so there's no one-stop-shop for job status.

**Comment by j-tai** [comment]
Hmmm, that's a tricky problem. Right now, girlboss is designed such that a `Job` stores the job's current status and its `JoinHandle`. However, in actix-rt, `JoinHandle` is not `Send`, but in theory, the job's current status could be.

I'll have to think about how to solve this in girlboss's API -- I somehow have to make "`Job` without the join handle" implement Send...

I'll look into it!

**Comment by j-tai** [comment]
@bburdette I've released girlboss 1.0.0-alpha.4, with a few changes:

* `Monitor` no longer needs a `Runtime` generic argument
* `Girlboss` can now store monitors rather than jobs: `girlboss::Girlboss<K, Monitor>` should implement `Send + Sync`, allowing you to query the job status from any thread.

Let me know how it works out! And thank you for the feedback!

**Comment by bburdette** [comment]
Ok job tracking is go!   

But its a mixed bag as far as my apps.  In the actix_web server the sync process is kicked off and runs.  But in tauri the task never starts.  

I recently discovered that actix_web doesn't actually use actix_rt in its handlers anymore, and hasn't for a few years.  News to me.  Perhaps relevant.

On the tauri side, I'm [spawning a thread](https://github.com/bburdette/tauri-zknotes/blob/12d8d074896ac280f8f1ecd23fbb9d1731bdb70d/tauri/src-tauri/src/commands.rs#L259) to handle a message, and in that thread I make a new actix_rt System, and it calls the same [gb start](https://github.com/bburdette/zknotes/blob/07846457943f08fe3f2980fd16526a52ab68fd5d/server-lib/src/interfaces.rs#L382) that works in actix_web mode.

**Comment by j-tai** [comment]
Okay, I took a look at your code (on the `gb-actix-rt` branch), and I think I see the issue.

You're creating an actix-rt `System` in the thread. Then, you spawn the girlboss `Job` within that system. Next, you [`block_on` the future returned by `zk_interface_loggedin`](https://github.com/bburdette/tauri-zknotes/blob/12d8d074896ac280f8f1ecd23fbb9d1731bdb70d/tauri/src-tauri/src/commands.rs#L266C7-L266C25), but this does not wait for the job to complete -- the future merely starts the job and then resolves. Then, the thread terminates, destroying the `System` along with it, leaving no chance for the `System` to start polling (i.e., running) the `Job`.

Here are some options:

* You could make the thread wait for the job to complete rather than just "spawning and forgetting" it.
* After the `rt.block_on` call, use [`rt.run()`](https://docs.rs/actix-rt/2.10.0/actix_rt/struct.SystemRunner.html#method.run) to allow the `System` to run its event loop, thereby running the `Job`. At the end of the `Job`'s code, you might want to run `actix_rt::System::current().stop()` to make it exit the event loop, thereby making `rt.run()` return (not 100% sure if this is necessary).

Both of these methods will keep the thread (and hence the `System`) alive until the job completes. Hence, if you still want to run the job asynchronously, you might not want to `join()` the thread right after spawning it.

**Comment by bburdette** [comment]
Thanks for the help!  Things are working now, though the code is still sloppy.  

So odd a System can be destroyed, yet still be used, and the result is silent failure.  

At any rate, got a chance to play around with this today, and ended up introducing a [second thread](https://github.com/bburdette/zknotes/blob/28f9e727d3956b26b8bbe107f9d458e9b01e73a8/server-lib/src/interfaces.rs#L387) and actix_rt::System.  The first thread/System exists since there are non-send futures used in zk_interface_loggedin.  This thread is expected to kick off the job and return the job id right away.  

A second thread is introduced to maintain a second actix_rt System while the sync job runs.  

And you were right about needing `actix_rt::System::current().stop()`.  Without it, the `rt.run()` never returns, and presumably the thread sits there forever wasting resources.

**Comment by j-tai** [comment]
Sounds good!

> the code is still sloppy.

I agree, and I think the root cause of the ugliness is because the 3rd-party libraries use non-Send futures, while your code runs on tokio (presumably), which requires Send futures. I think you previously mentioned `awc` being one of these libraries.

Since these libraries can't run in tokio, you have to spawn a new thread and create a new actix-rt `System` to use those libraries. A permanent solution would be to replace these libraries with alternatives that support tokio (perhaps `reqwest`).

**Comment by bburdette** [comment]
Yeah I started with reqwest but switched to awc because of [streaming issues](https://github.com/seanmonstar/reqwest/issues/1969).  Apparently that's fixed in reqwest now.  The other culprit is rusqlite, I think partly because of the underlying C implementation.  There's a tokio-rusqlite wrapper for it that basically runs a second thread and sends requests there with mpsc.  That's a questionable gain over just spawning a thread, but its an option.

At any rate, good to have options so I can get it working now and hopefully phase in to more elegant solutions later.

**Comment by j-tai** [comment]
Sounds good! I personally use `sqlx` for SQLite.

Happy coding!! :3
